return {
	{
		"tpope/vim-sleuth",
		-- This can cause some issues with file types not respecting the
		-- desired global indentation. This also is what causes the
		-- initial text when nvim is open to go away without input.
		-- Because this also messes with the filetype, it can also
		-- cause color scheme colors to not load correctly.
		enabled = false,
	},
	{
		"akinsho/bufferline.nvim",
		enabled = false,
	},
	{
		"echasnovski/mini.pairs",
		enabled = false,
	},
	{
		"folke/flash.nvim",
		enabled = false,
	},
	{
		"echasnovski/mini.comment",
		enabled = false,
	},
	{
		"nvimtools/none-ls.nvim",
		enabled = false,
	},
	-- { "cmp-buffer", enabled = false },
	-- { "cmp-nvim-lsp", enabled = false },
	-- { "cmp-path", enabled = false },
	-- { "cmp_luasnip", enabled = false },
	-- { "conform.nvim", enabled = false },
	-- { "dashboard-nvim", enabled = false },
	-- { "friendly-snippets", enabled = false },
	-- { "gitsigns.nvim", enabled = false },
	-- { "gruvbox-material", enabled = false },
	-- { "gruvbox.nvim", enabled = false },
	-- { "indent-blankline.nvim", enabled = false },
	-- { "lazy.nvim", enabled = false },
	-- { "LazyVim", enabled = false },
	-- { "lualine.nvim", enabled = false },
	-- { "LuaSnip", enabled = false },
	-- { "mason-lspconfig.nvim", enabled = false },
	-- { "mason.nvim", enabled = false },
	-- { "mini.ai", enabled = false },
	-- { "mini.indentscope", enabled = false },
	-- { "molokai", enabled = false },
	-- { "neoconf.nvim", enabled = false },
	-- { "neodev.nvim", enabled = false },
	-- { "noice.nvim", enabled = false },
	-- { "nui.nvim", enabled = false },
	-- { "nvim-cmp", enabled = false },
	-- { "nvim-lint", enabled = false },
	-- { "nvim-lspconfig", enabled = false },
	-- { "nvim-notify", enabled = false },
	-- { "nvim-treesitter", enabled = false },
	-- { "nvim-treesitter-context", enabled = false },
	-- { "nvim-treesitter-textobjects", enabled = false },
	-- { "nvim-ts-autotag", enabled = false },
	-- { "nvim-web-devicons", enabled = false },
	-- { "persistence.nvim", enabled = false },
	-- { "plenary.nvim", enabled = false },
	-- { "telescope-fzf-native.nvim", enabled = false },
	-- { "telescope.nvim", enabled = false },
	-- { "todo-comments.nvim", enabled = false },
	-- { "trouble.nvim", enabled = false },
	-- { "vim-aldmeris", enabled = false },
	-- { "vim-illuminate", enabled = false },
	-- { "vim-moonfly-colors", enabled = false },
	-- { "vim-nightfly-guicolors", enabled = false },
	-- { "which-key.nvim", enabled = false },
}
